-- Active: 1741846246306@@127.0.0.1@3306@seeyon
DROP DATABASE IF EXISTS `sync`;

CREATE DATABASE `sync` CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

USE `sync`;

CREATE TABLE `MID_ORG_GROUP` (
    `ID` VARCHAR(255) PRIMARY KEY NOT NULL COMMENT '主键',
    `NAME` VARCHAR(255) NOT NULL COMMENT '名称',
    `CODE` VARCHAR(255) NOT NULL COMMENT '编码',
    `SHORT_NAME` VARCHAR(255) COMMENT '简称',
    `PARENTID` VARCHAR(255) COMMENT '上级主键',
    `IS_ENABLE` INT DEFAULT 1 NOT NULL COMMENT '是否启用',
    `IS_DELETED` INT DEFAULT 0 NOT NULL COMMENT '是否删除',
    `UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '集团表';

INSERT INTO
    `MID_ORG_GROUP` (`ID`, `NAME`, `CODE`)
VALUES ('G1', '集团1', 'JT1');

CREATE TABLE `MID_ORG_UNIT` (
    `ID` VARCHAR(255) PRIMARY KEY NOT NULL COMMENT '主键',
    `NAME` VARCHAR(255) NOT NULL COMMENT '名称',
    `CODE` VARCHAR(255) NOT NULL COMMENT '编码',
    `SHORT_NAME` VARCHAR(255) COMMENT '简称',
    `GROUPID` VARCHAR(255) COMMENT '集团主键',
    `PARENTID` VARCHAR(255) COMMENT '上级主键',
    `IS_ENABLE` INT DEFAULT 1 NOT NULL COMMENT '是否启用',
    `IS_DELETED` INT DEFAULT 0 NOT NULL COMMENT '是否删除',
    `UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '单位表';

INSERT INTO
    `MID_ORG_UNIT` (
        `ID`,
        `NAME`,
        `CODE`,
        `GROUPID`
    )
VALUES ('U1', '单位1', 'DW1', 'G1');

CREATE TABLE `MID_ORG_DEPARTMENT` (
    `ID` VARCHAR(255) PRIMARY KEY NOT NULL COMMENT '主键',
    `NAME` VARCHAR(255) NOT NULL COMMENT '名称',
    `CODE` VARCHAR(255) NOT NULL COMMENT '编码',
    `UNITID` VARCHAR(255) COMMENT '公司主键',
    `GROUPID` VARCHAR(255) COMMENT '集团主键',
    `PARENTID` VARCHAR(255) COMMENT '上级部门主键',
    `DEPARTMANAGERS` VARCHAR(255) COMMENT '部门负责人',
    `IS_ENABLE` INT DEFAULT 1 NOT NULL COMMENT '是否启用',
    `IS_DELETED` INT DEFAULT 0 NOT NULL COMMENT '是否删除',
    `UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '部门表';

INSERT INTO
    `MID_ORG_DEPARTMENT` (
        `ID`,
        `NAME`,
        `CODE`,
        `UNITID`,
        `GROUPID`
    )
VALUES (
        'D1',
        '部门1',
        'BM1',
        'U1',
        'G1'
    );

-- 未同步，未知问题
CREATE TABLE `MID_ORG_JOB` (
    `ID` VARCHAR(255) PRIMARY KEY NOT NULL COMMENT '主键',
    `NAME` VARCHAR(255) NOT NULL COMMENT '名称',
    `CODE` VARCHAR(255) NOT NULL COMMENT '编码',
    `UNITID` VARCHAR(255) NOT NULL COMMENT '公司主键',
    `IS_ENABLE` INT DEFAULT 1 NOT NULL COMMENT '是否启用',
    `IS_DELETED` INT DEFAULT 0 NOT NULL COMMENT '是否删除',
    `UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '职务表';

INSERT INTO
    `MID_ORG_JOB` (
        `ID`,
        `NAME`,
        `CODE`,
        `UNITID`
    )
VALUES ('J1', '职务1', 'ZW1', 'G1');

CREATE TABLE `MID_ORG_POST` (
    `ID` VARCHAR(255) PRIMARY KEY NOT NULL COMMENT '主键',
    `NAME` VARCHAR(255) NOT NULL COMMENT '名称',
    `CODE` VARCHAR(255) NOT NULL COMMENT '编码',
    `ENTITYID` VARCHAR(255) NOT NULL COMMENT '所属组织主键',
    `DEPARTMENTID` VARCHAR(255) COMMENT '所属部门主键',
    `IS_RESPONPOST` INT DEFAULT 0 NOT NULL COMMENT '是否部门负责岗位',
    `IS_ENABLE` INT DEFAULT 1 NOT NULL COMMENT '是否启用',
    `IS_DELETED` INT DEFAULT 0 NOT NULL COMMENT '是否删除',
    `UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '岗位表';

INSERT INTO
    `MID_ORG_POST` (
        `ID`,
        `NAME`,
        `CODE`,
        `ENTITYID`,
        `DEPARTMENTID`
    )
VALUES (
        'P1',
        '岗位1',
        'GW1',
        'U1',
        'D1'
    );

CREATE TABLE `MID_ORG_PERSON_BASE` (
    `ID` VARCHAR(255) PRIMARY KEY NOT NULL COMMENT '主键',
    `UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间',
    `USED_NAME` VARCHAR(255) COMMENT '曾用名',
    `AGE` INT COMMENT '年龄',
    `GENDER` INT COMMENT '性别',
    `BIRTHDAY` DATE COMMENT '出生日期',
    `NATION` VARCHAR(255) COMMENT '民族',
    `BIRTHPLACE` VARCHAR(255) COMMENT '籍贯',
    `ID_CARD` VARCHAR(18) COMMENT '身份证',
    `MARRIAGE` INT COMMENT '婚姻状态',
    `WORK_STARTING_DATE` DATE COMMENT '入职时间',
    `WORKING_TIME` INT COMMENT '工龄',
    `SPECIALTY` VARCHAR(255) COMMENT '专业',
    `HOBBY` VARCHAR(255) COMMENT '业余爱好',
    `RECORD_WAGE` INT COMMENT '档案工资',
    `EMAIL` VARCHAR(255) COMMENT '邮箱',
    `TELPHONE` VARCHAR(255) COMMENT '手机号',
    `OFFICENUMBER` VARCHAR(255) COMMENT '办公电话',
    `ADDRESS` VARCHAR(255) COMMENT '家庭地址',
    `POSTALCODE` VARCHAR(255) COMMENT '邮编',
    `WEBSITE` VARCHAR(255) COMMENT '个人网页',
    `BLOG` VARCHAR(255) COMMENT '博客',
    `QQ` VARCHAR(255) COMMENT 'QQ',
    `MSN` VARCHAR(255) COMMENT 'msn',
    `WEIBO` VARCHAR(255) COMMENT '微博',
    `WEIXIN` VARCHAR(255) COMMENT '微信',
    `LOCATION` VARCHAR(255) COMMENT '工作地',
    `REPORTER` VARCHAR(255) COMMENT '汇报人',
    `DEGREE` INT COMMENT '最高学历',
    `POSTADDRESS` VARCHAR(255) COMMENT '邮寄地址',
    `POLITICS` INT COMMENT '政治面貌',
    `YEARSOFSERVICE` VARCHAR(255) COMMENT '扩展信息10',
    `EXT_ATTR_1` VARCHAR(255) COMMENT '扩展信息1',
    `EXT_ATTR_2` VARCHAR(255) COMMENT '扩展信息2',
    `EXT_ATTR_3` VARCHAR(255) COMMENT '扩展信息3',
    `EXT_ATTR_4` VARCHAR(255) COMMENT '扩展信息4',
    `EXT_ATTR_5` VARCHAR(255) COMMENT '扩展信息5'
) COMMENT '人员基础信息表';

INSERT INTO
    `MID_ORG_PERSON_BASE` (`ID`, `USED_NAME`)
VALUES ('PB1', "张三");

CREATE TABLE `MID_ORG_PERSON` (
    `ID` VARCHAR(255) PRIMARY KEY NOT NULL,
    `PERSON_BASEID` VARCHAR(255) NOT NULL COMMENT '基础信息主键',
    `STATE` INT DEFAULT 1 NOT NULL COMMENT '状态',
    `NAME` VARCHAR(255) NOT NULL COMMENT '姓名',
    `CODE` VARCHAR(255) NOT NULL COMMENT '编码',
    `DEPARTMENTID` VARCHAR(255) NOT NULL COMMENT '所在部门',
    `UNITID` VARCHAR(255) COMMENT '公司主键',
    `GROUPID` VARCHAR(255) COMMENT '集团主键',
    `JOBID` VARCHAR(255) NOT NULL COMMENT '职务级别主键',
    `POSTID` VARCHAR(255) NOT NULL COMMENT '岗位主键',
    `IS_ENABLE` INT DEFAULT 1 NOT NULL COMMENT '是否启用',
    `IS_DELETED` INT DEFAULT 0 NOT NULL COMMENT '是否删除',
    `IS_FINISH` INT DEFAULT 0 NOT NULL COMMENT '任职结束标识',
    `LOGIN_NAME` VARCHAR(255) NOT NULL COMMENT '登录名',
    `UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '人员任职信息表';

INSERT INTO
    `MID_ORG_PERSON` (
        `ID`,
        `PERSON_BASEID`,
        `NAME`,
        `CODE`,
        `LOGIN_NAME`,
        `DEPARTMENTID`,
        `UNITID`,
        `GROUPID`,
        `JOBID`,
        `POSTID`
    )
VALUES (
        'X1',
        'PB1',
        '张三',
        'z3',
        'zhangsan',
        'D1',
        'U1',
        'G1',
        'J1',
        'P1'
    );

CREATE TABLE `MID_ORG_PERSON_PART` (
    `ID` VARCHAR(255) PRIMARY KEY NOT NULL COMMENT '主键',
    `PERSONID` VARCHAR(255) NOT NULL COMMENT '人员主键',
    `DEPARTMENTID` VARCHAR(255) NOT NULL COMMENT '部门主键',
    `UNITID` VARCHAR(255) NOT NULL COMMENT '单位主键',
    `JOBID` VARCHAR(255) COMMENT '岗位主键',
    `POSTID` VARCHAR(255) NOT NULL COMMENT '职位名称',
    `IS_DELETED` INT DEFAULT 0 NOT NULL COMMENT '是否删除',
    `IS_FINISH` INT DEFAULT 0 NOT NULL COMMENT '任职结束标识',
    `UPDATE_TIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '修改时间'
) COMMENT '人员兼职表';

SHOW VARIABLES LIKE '%lower%';